[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Functions istisnası
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# SPA yönlendirmesi
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
